ENV["SINATRA_ENV"] ||= "development"

require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Drop databases"
task :drop do
  puts "dumping data...."
  system "rm db/schema.rb && development.sqlite"
end

desc "Migrates Databases"
task :migrations do 
  puts "migrating databases...."
  system "rake db:migrate"
end

desc "Resets database and starts shotgun"
task :reset_db do
  puts "resetting data..."
  Rake::Task["drop"].execute
  Rake::Task["migrations"].execute
  system "shotgun"
end